### ISSUE TITLE
[QUESTION] Local icons not found

### ISSUE THREAD

**Issue by lukasitaly** [hywax/mafl#128]
### Question

So my folder structure is as follows:

- [FOLDER] icons
- [FOLDER] favicons
- [FILE] config.yml
- [FILE] compose.yml

This is my compose:
```yml
services:
  mafl:
    container_name: mafl
    image: hywax/mafl
    restart: unless-stopped
    ports:
      - '3212:3000'
    volumes:
      - ./config.yml:/app/data/config.yml
      - ./icons:/app/public/icons
      - ./favicons:/app/public/favicons
```
For the config I use the guide on your website. One example that didn't work:
```yml
    - title: Audiobookshelf
      description: Audiobooks
      link: https://audiobooks.hoferlukas.org/
      icon:
        url: ./icons/audiobookshelf.png
        wrap: true
        color: '#3dbcf3'
      status:
        enabled: true
```
No matter how I try it doesn't seem to find the file. And the file exists with this exact name. I tried to play around with the path in the browser-inspector but no matter what the file is not found. What am I doing wrong?

### Category

Using Icons
