### ISSUE TITLE
[BUG] `Error: Config not found` on fresh install

### ISSUE THREAD

**Issue by MontejoJorge** [hywax/mafl#143]
### Environment

Self-Hosted (Docker)

### System

Raspberry pi 4 - Docker 27.2.1

### Version

0.15.4

### Describe the problem

Using this docker compose i got the error: **_Error: Config not found_**
```
version: "3.8"
services:
  mafl:
    restart: unless-stopped
    image: ghcr.io/hywax/mafl:v0.15.4
    container_name: mafl
    ports:
      - 61983:3000
    volumes:
      - /home/jorge/app-data/mafl:/app/data
networks: {}
```
