### ISSUE TITLE
[FEATURE_REQUEST] get status icon by pinging an outside url

### ISSUE THREAD

**Issue by edbr-xyz** [hywax/mafl#170]
### Is your feature request related to a problem? If so, please describe.

When I set my services' links to be URLs rather than IP:PORTs (e.g. service.domain.tld), it always shows them with a red status.

### Describe the solution you'd like

It would be great if any link worked.

Maybe there could be a seperate link to check like:
```yaml
link: 'https://service.domain.tld'
  status:
    enabled: true
    url: '192.168.1.10:8080'
```

or maybe it could just work with the link.

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement

None
