### ISSUE TITLE
[QUESTION] <Error500>

### ISSUE THREAD

**Issue by klsdfjo** [hywax/mafl#43]
### Question

Error display:
```
谬误 500

哎呀！出现意外错误
[转到文档 →](https://mafl.hywax.space/)
{
 "services": {
  "_errors": [
   "Required",
   "Required"
  ]
 }
}
```

My docker compose :
```
version: '3.8'

services:
  mafl:
    image: hywax/mafl
    restart: unless-stopped
    ports:
      - '16010:3000'
    volumes:
      - ./config.yml:/app/data/config.yml
```

My Linux Cpu:

发行版本 debian-12.4
--
内核版本 6.1.0-10-amd64
系统类型 x86_64

### Category

Setup and Deployment
